<?php

/**
 * PDO database wrapper providing a singleton connection and convenience query helpers.
 *
 * @package CM-IMAP\Lib
 */
class Database {
    /** @var PDO|null Singleton PDO instance */
    private static ?PDO $instance = null;

    /**
     * Return the shared PDO instance, creating it on first call.
     *
     * Connection settings are loaded from config/database.php. The connection
     * uses exceptions for errors, associative fetch mode, and native prepared
     * statements.
     *
     * @return PDO
     */
    public static function getInstance(): PDO {
        if (self::$instance === null) {
            $cfg = require __DIR__ . '/../config/database.php';
            $dsn = "mysql:host={$cfg['host']};port={$cfg['port']};dbname={$cfg['name']};charset={$cfg['charset']}";
            self::$instance = new PDO($dsn, $cfg['user'], $cfg['password'], [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
            ]);
        }
        return self::$instance;
    }

    /** Convenience: prepare + execute, return statement */
    /**
     * Prepare and execute a query, returning the executed statement.
     *
     * @param  string  $sql    Parameterised SQL statement.
     * @param  array   $params Positional or named bind values.
     * @return PDOStatement
     */
    public static function query(string $sql, array $params = []): PDOStatement {
        $stmt = self::getInstance()->prepare($sql);
        $stmt->execute($params);
        return $stmt;
    }

    /**
     * Execute a SELECT and return all matching rows.
     *
     * @param  string $sql
     * @param  array  $params
     * @return array<int, array<string, mixed>>
     */
    public static function fetchAll(string $sql, array $params = []): array {
        return self::query($sql, $params)->fetchAll();
    }

    /**
     * Execute a SELECT and return the first row, or null if no match.
     *
     * @param  string $sql
     * @param  array  $params
     * @return array<string, mixed>|null
     */
    public static function fetchOne(string $sql, array $params = []): ?array {
        $row = self::query($sql, $params)->fetch();
        return $row ?: null;
    }

    /**
     * Execute a SELECT and return the value of the first column of the first row,
     * or null if no match.
     *
     * @param  string $sql
     * @param  array  $params
     * @return mixed
     */
    public static function fetchScalar(string $sql, array $params = []): mixed {
        $row = self::query($sql, $params)->fetch(PDO::FETCH_NUM);
        return $row ? $row[0] : null;
    }

    /**
     * Return the auto-increment ID generated by the last INSERT.
     *
     * @return string
     */
    public static function lastInsertId(): string {
        return self::getInstance()->lastInsertId();
    }

    /**
     * Begin a database transaction.
     *
     * @return void
     */
    public static function beginTransaction(): void {
        self::getInstance()->beginTransaction();
    }

    /**
     * Commit the current transaction.
     *
     * @return void
     */
    public static function commit(): void {
        self::getInstance()->commit();
    }

    /**
     * Roll back the current transaction.
     *
     * @return void
     */
    public static function rollback(): void {
        self::getInstance()->rollBack();
    }

    /**
     * Retrieve a value from the key/value settings table.
     *
     * @param  string $key     Setting name.
     * @param  mixed  $default Value to return when the key does not exist.
     * @return mixed
     */
    public static function getSetting(string $key, mixed $default = null): mixed {
        $val = self::fetchScalar('SELECT `value` FROM settings WHERE `key` = ?', [$key]);
        return $val !== null ? $val : $default;
    }
}
